GOOGLE_CLIENT_ID: 587130802745-t6vrap8o2bn99shbrbaahj627k49tj28.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: GHAYDc_B1uC6NRMT-uCxgbtM
GOOGLE_APP_ID: AIzaSyCPUorwJDHhh_YNsWxV2OTVAUZYGEoKBRk
FACEBOOK_APP_ID: 708682375838063
NEW_RELIC_LICENSE_KEY: 'ba9e8025df7a625aea5e4211696f928ab390b8aa'
SENDGRID_USERNAME: evrystep_test_user
SENDGRID_PASS: evrystepstag1ng