development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: guru_development
  pool: 5
  username: postgres
  password: Evrystepg0lden

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: guru_test
  pool: 5
  username: 
  password: 