development:
  adapter: postgresql
  encoding: unicode
  database: guru_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: guru_test
  pool: 5
  username: root
  password:
