# encoding: UTF-8
# This file is auto-generated from the current content of the database. Instead
# of editing this file, please use the migrations feature of Seed Migration to
# incrementally modify your database, and then regenerate this seed file.
#
# If you need to create the database on another system, you should be using
# db:seed, not running all the migrations from scratch. The latter is a flawed
# and unsustainable approach (the more migrations you'll amass, the slower
# it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Base.transaction do

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:25Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Rerum ipsam nihil aut nihil distinctio qui sequi.", "email"=>"orlando@steuberbergstrom.net", "encrypted_password"=>"$2a$10$Nk5dehoWRF5R5RxGXJnMLerGrOUpMwRbZo3cNquI0AGPZZX65oXwC", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Jeanie", "id"=>1, "last_name"=>"Bogisich", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:25Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Sit illum est eos.", "email"=>"albert@greenholt.com", "encrypted_password"=>"$2a$10$bDMMT0x2RcgBuT5Z/QWbbuDhWU.jOH2VGwhDJVolMJJ3R7Tq6WodG", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Leon", "id"=>2, "last_name"=>"Jacobs", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Quam accusantium in dolorem in et commodi qui.", "email"=>"jevon_leannon@balistreri.name", "encrypted_password"=>"$2a$10$dMa1qdUKpj.fr.gsW.CTD.Bhjmj5KjqxWoBQtF1ezJlv.hBzIhjO6", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Nedra", "id"=>3, "last_name"=>"Murphy", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Voluptate quas sint voluptatem inventore deleniti voluptas.", "email"=>"laron@mueller.name", "encrypted_password"=>"$2a$10$DeoOy7P0auk7vyYxKQOiQe69eww4bfuCYaE6QAulDxZsCgpr8JDde", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Darwin", "id"=>4, "last_name"=>"Pfannerstill", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Necessitatibus sunt sapiente ut facere non aliquam.", "email"=>"aglae@swift.net", "encrypted_password"=>"$2a$10$SuL.TxsXbIjBdHa0iw0qI.Vk1iSYY8VxV3T9m55ZTILZ0AMYwFZx2", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Pierre", "id"=>5, "last_name"=>"Douglas", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Accusamus delectus amet atque dolores adipisci sed id.", "email"=>"sedrick@bauch.org", "encrypted_password"=>"$2a$10$FTS5mYHVr2Aa4mul8eVA.eH7HA1uBZkpxoOIKnjlX3wSM7TdFqJoO", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Houston", "id"=>6, "last_name"=>"Moore", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Sed omnis ea nihil tenetur consequuntur.", "email"=>"zoey@sawayn.name", "encrypted_password"=>"$2a$10$SqzfiLwHoI4W9BQPgX/8aOXfP1Uaj3KWLS./ewIUVhtAZrf9a/LU6", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Peggie", "id"=>7, "last_name"=>"Spinka", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Distinctio accusantium laborum amet aut iste exercitationem ipsa voluptates.", "email"=>"cecelia_roob@hoeger.info", "encrypted_password"=>"$2a$10$7qHF39aLmP.V/JkFc3gdQ.rv7SLyuX1O55eywBz9AOQU1pT545opK", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Herbert", "id"=>8, "last_name"=>"Cartwright", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Est pariatur natus quia placeat non.", "email"=>"myrtis_kertzmann@kshlerin.biz", "encrypted_password"=>"$2a$10$28WOYNO9.JZPAv9ycXrOI.R3rnuXBsW.KDy.g.L3KEdknTK5kj.l2", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Bernhard", "id"=>9, "last_name"=>"Pagac", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  User.create({"avatar_content_type"=>nil, "avatar_file_name"=>nil, "avatar_file_size"=>nil, "avatar_updated_at"=>nil, "bio"=>nil, "categories"=>nil, "claim_email"=>nil, "claim_token"=>nil, "claim_user"=>nil, "cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "current_sign_in_at"=>nil, "current_sign_in_ip"=>nil, "description"=>"Iure suscipit veniam dicta voluptas sed dolor sunt.", "email"=>"forrest_johnson@kulashayes.net", "encrypted_password"=>"$2a$10$mMZ0phppaTwCPphdLXkjP.QvF3TKRPFC.iW0m7xYMOAIq.XnTncM6", "expires_at"=>nil, "featured_artist"=>nil, "first_name"=>"Jalon", "id"=>10, "last_name"=>"Powlowski", "last_sign_in_at"=>nil, "last_sign_in_ip"=>nil, "location"=>nil, "provider"=>nil, "remember_created_at"=>nil, "reset_password_sent_at"=>nil, "reset_password_token"=>nil, "sign_in_count"=>0, "token"=>nil, "uid"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)
  ActiveRecord::Base.connection.reset_pk_sequence!('users')

  Interest.create({"cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "description"=>"Minus autem qui facere vero similique architecto fugiat.", "history"=>nil, "id"=>1, "name"=>"nihil", "quote_author"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  Interest.create({"cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "description"=>"Fugit nihil eos et.", "history"=>nil, "id"=>2, "name"=>"ipsam", "quote_author"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  Interest.create({"cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "description"=>"Quia est excepturi sunt vitae rem laboriosam quidem molestiae.", "history"=>nil, "id"=>3, "name"=>"est", "quote_author"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  Interest.create({"cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "description"=>"Impedit consequatur qui ut est.", "history"=>nil, "id"=>4, "name"=>"delectus", "quote_author"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)

  Interest.create({"cover_photo_content_type"=>nil, "cover_photo_file_name"=>nil, "cover_photo_file_size"=>nil, "cover_photo_updated_at"=>nil, "created_at"=>"2016-01-29T07:46:26Z", "description"=>"Rerum doloribus molestiae minima sunt consequatur qui voluptas.", "history"=>nil, "id"=>5, "name"=>"veritatis", "quote_author"=>nil, "updated_at"=>"2016-01-29T07:46:26Z"}, :without_protection => true)
  ActiveRecord::Base.connection.reset_pk_sequence!('interests')

  UserInterest.create({"created_at"=>"2016-01-29T07:46:26Z", "id"=>1, "interest_id"=>5, "updated_at"=>"2016-01-29T07:46:26Z", "user_id"=>1}, :without_protection => true)

  UserInterest.create({"created_at"=>"2016-01-29T07:46:26Z", "id"=>2, "interest_id"=>1, "updated_at"=>"2016-01-29T07:46:26Z", "user_id"=>1}, :without_protection => true)

  UserInterest.create({"created_at"=>"2016-01-29T07:46:26Z", "id"=>3, "interest_id"=>2, "updated_at"=>"2016-01-29T07:46:26Z", "user_id"=>1}, :without_protection => true)

  UserInterest.create({"created_at"=>"2016-01-29T07:46:26Z", "id"=>4, "interest_id"=>3, "updated_at"=>"2016-01-29T07:46:26Z", "user_id"=>1}, :without_protection => true)
  ActiveRecord::Base.connection.reset_pk_sequence!('user_interests')
end

SeedMigration::Migrator.bootstrap(20151230005455)
